DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE BATCH_STEP_EXECUTION;
DROP TABLE BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE BATCH_JOB_EXECUTION;
DROP TABLE BATCH_JOB_INSTANCE;

DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_SEQ;

DROP TABLE CUSTOMERS;
DROP TABLE CUSTOMER_SYNCUP;
DROP TABLE CUSTOMER_STAGING;
DROP TABLE CUSTOMER_PUBLISH;

CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION         NUMBER(19,0),
    JOB_NAME        VARCHAR2(100 CHAR) NOT NULL,
    JOB_KEY         VARCHAR2(32 CHAR) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) SEGMENT CREATION IMMEDIATE;

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION          NUMBER(19,0),
    JOB_INSTANCE_ID  NUMBER(19,0) NOT NULL,
    CREATE_TIME      TIMESTAMP(9) NOT NULL,
    START_TIME       TIMESTAMP(9) DEFAULT NULL,
    END_TIME         TIMESTAMP(9) DEFAULT NULL,
    STATUS           VARCHAR2(10 CHAR),
    EXIT_CODE        VARCHAR2(2500 CHAR),
    EXIT_MESSAGE     VARCHAR2(2500 CHAR),
    LAST_UPDATED     TIMESTAMP(9),
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
) SEGMENT CREATION IMMEDIATE;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
    PARAMETER_NAME   VARCHAR(100 CHAR
) NOT NULL ,
	PARAMETER_TYPE VARCHAR(100 CHAR) NOT NULL ,
	PARAMETER_VALUE VARCHAR(2500 CHAR) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) SEGMENT CREATION IMMEDIATE;

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION            NUMBER(19,0) NOT NULL,
    STEP_NAME          VARCHAR2(100 CHAR) NOT NULL,
    JOB_EXECUTION_ID   NUMBER(19,0) NOT NULL,
    CREATE_TIME        TIMESTAMP(9) NOT NULL,
    START_TIME         TIMESTAMP(9) DEFAULT NULL,
    END_TIME           TIMESTAMP(9) DEFAULT NULL,
    STATUS             VARCHAR2(10 CHAR),
    COMMIT_COUNT       NUMBER(19,0),
    READ_COUNT         NUMBER(19,0),
    FILTER_COUNT       NUMBER(19,0),
    WRITE_COUNT        NUMBER(19,0),
    READ_SKIP_COUNT    NUMBER(19,0),
    WRITE_SKIP_COUNT   NUMBER(19,0),
    PROCESS_SKIP_COUNT NUMBER(19,0),
    ROLLBACK_COUNT     NUMBER(19,0),
    EXIT_CODE          VARCHAR2(2500 CHAR),
    EXIT_MESSAGE       VARCHAR2(2500 CHAR),
    LAST_UPDATED       TIMESTAMP(9),
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) SEGMENT CREATION IMMEDIATE;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  NUMBER(19,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR2(2500 CHAR) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
) SEGMENT CREATION IMMEDIATE;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   NUMBER(19,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR2(2500 CHAR) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) SEGMENT CREATION IMMEDIATE;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 ORDER NOCYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 ORDER NOCYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 ORDER NOCYCLE;

CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID      NUMBER PRIMARY KEY,
    SURNAME          VARCHAR2(50),
    C_SCORE          NUMBER,
    COUNTRY          VARCHAR2(50),
    GENDER           VARCHAR2(10),
    AGE              NUMBER,
    TENURE           NUMBER,
    BALANCE          NUMBER,
    HAS_CREDIT_CARD  NUMBER(1),
    IS_ACTIVE        NUMBER(1),
    ESTIMATED_SALARY NUMBER
);

CREATE TABLE CUSTOMER_SYNCUP
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    SURNAME     VARCHAR2(50),
    C_SCORE     NUMBER,
    AGE         NUMBER,
    TENURE      NUMBER,
    STATUS      VARCHAR2(2) --NEW (NW), PENDING (PN), COMPLETED (CP), NOT_APPLICABLE (NA)
);

CREATE TABLE CUSTOMER_STAGING
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    SURNAME     VARCHAR2(50),
    C_SCORE     NUMBER,
    AGE         NUMBER,
    TENURE      NUMBER,
    STATUS      VARCHAR2(2) --NEW (NW), PENDING (PN), COMPLETED (CP), NOT_APPLICABLE (NA)
);

CREATE TABLE CUSTOMER_PUBLISH
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    SURNAME     VARCHAR2(50),
    C_SCORE     NUMBER,
    AGE         NUMBER,
    TENURE      NUMBER,
    STATUS      VARCHAR2(2) --NEW (NW), PENDING (PN), COMPLETED (CP), NOT_APPLICABLE (NA)
);
